spring:
  artemis:
    mode: native
    broker-url: tcp://localhost:61616
    user: artemis
    password: artemis
  jms:
    pub-sub-domain: true

producer:
  jms:
    message-producer: messageProducer
    message-reply-user: messageReplyUser
    routing-context:
      address: messageAddress
      routing-type: MULTICAST

subscriber:
  jms:
    routing-context:
      address: messageAddress
    subscription: topic
